### PR TITLE
Ecas

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

Add ECAS documentation

### CODE REVIEW

**Comment by enolfc** [comment]
Still need to be clarified how to deal with hardcoded password.

**Comment by enolfc** [comment]
And #18 should be merged before :)

**Comment by enolfc** [comment]
Hardcoded password removed

**Review by glarocca — DISMISSED** [review]
Accepted changes

**Comment by enolfc** [comment]
@glarocca could you re-approve? I rebased the change for #18 and github is not that smart

**Review by glarocca — APPROVED** [review]

**Pull request merged**
